---

- name: create certificates directory
  file:
    path: "{{ cert_dir }}"
    state: directory

- name: generate ca private key
  openssl_privatekey:
    path: "{{ cert_dir }}/ca.key"

- name: generate self signed ca
  openssl_certificate:
    path: "{{ cert_dir }}/ca.crt"
    privatekey_path: "{{ cert_dir }}/ca.key"
    provider: selfsigned

- name: generate host private key
  openssl_privatekey:
    path: "{{ cert_dir }}/{{ ansible_ssh_host}}.key"

- name: generate host csr
  openssl_csr:
    path: "{{ cert_dir }}/{{ ansible_ssh_host }}.csr"
    privatekey_path: "{{ cert_dir }}/{{ ansible_ssh_host }}.key"
    common_name: "{{ ansible_ssh_host }}"
    subject_alt_name: IP:{{ ansible_ssh_host }}
    basic_constraints: CA:FALSE
    key_usage: 
      - digitalSignature
      - nonRepudiation
      - keyEncipherment
      - dataEncipherment
    extended_key_usage: 
      - serverAuth

- name: generate host certificate
  openssl_certificate:
    path: "{{ cert_dir }}/{{ ansible_ssh_host }}.crt"
    csr_path: "{{ cert_dir }}/{{ ansible_ssh_host}}.csr"
    ownca_path: "{{ cert_dir }}/ca.crt"
    ownca_privatekey_path: "{{ cert_dir }}/ca.key"
    provider: ownca
