---

- name: enable ip forward
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    state: present
    reload: yes

- name: disable firewall
  service:
    name: firewalld
    state: stopped

- name: disable selinux
  selinux:
    state: disabled
